services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"

  # Kafka container. Used to transfer/broker data/messages 
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    depends_on:
      - zookeeper
    env_file:
      - ./kafka.env
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      # limits the maximum heap-size, otherwise will continue to increase
      KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      #KAFKA_CREATE_TOPICS: "topic-test:1:1"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-consumer:
    build:
      context: ./DataConsumer
    container_name: kafka-consumer
    restart: always
    depends_on:
      - kafka



  kafka-producer:
    build:
      context: ./DataProducer
    container_name: kafka-producer
    restart: always
    depends_on:
      - kafka


  postgres:
      image: postgres
      container_name: postgres
      build:
        context: ./Postgres
      restart: always
      environment:
        POSTGRES_USER: postgres     
        POSTGRES_PASSWORD: postgres 
        POSTGRES_DB: postgres  
      ports:
        - '5432:5432'
      #volumes: 
      #  - data_sql:/var/lib/postgresql


  # kafka-connect container
  # this container is for the postgres sink
  kafka-connect-postgres-sink:
    build:
      context: ./KafkaConnect
    #image: my-kafka-connect-pg-sink
    image: confluentinc/cp-kafka-connect
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: my-connect-cluster 
      CONNECT_CONFIG_STORAGE_TOPIC: connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: connect-status
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181

      CONNECT_REST_ADVERTISED_HOST_NAME: docker
      CONNECT_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

#    env_file:
#      - ./KafkaConnect/KafkaConnectPostgresSink.env
    depends_on:
      - zookeeper
      - kafka
      - postgres
    restart: always
    volumes:
      - ./KafkaConnect/worker.properties:/worker.properties
      - ./KafkaConnect/connector.properties.d:/connector.properties.d
#      - ./KafkaConnect/worker.properties:/worker.properties
#      - ./KafkaConnect/connector.properties:/connector.properties
#      - ./kafka/kafka-connect-mqtt-source/custom_smt:/custom_smt/built-transformations